// fullstack-d3-advanced-code/13-using-d3-with-react-js/src/completed/Chart/Line.jsx
import React from "react"
import PropTypes from "prop-types"
import * as d3 from "d3"
import { accessorPropsType } from "./utils";

const Line = ({ type, data, xAccessor, yAccessor, y0Accessor, interpolation, ...props }) => {
  const lineGenerator = d3[type]()
    .x(xAccessor)
    .y(yAccessor)
    .curve(interpolation)

  if (type == "area") {
    lineGenerator
      .y0(y0Accessor)
      .y1(yAccessor)
  }

  return (
    <path {...props}
      className={`Line Line--type-${type}`}
      d={lineGenerator(data)}
    />
  )
}

Line.propTypes = {
  type: PropTypes.oneOf(["line", "area"]),
  data: PropTypes.array,
  xAccessor: accessorPropsType,
  yAccessor: accessorPropsType,
  y0Accessor: accessorPropsType,
  interpolation: PropTypes.func,
}

Line.defaultProps = {
  type: "line",
  y0Accessor: 0,
  interpolation: d3.curveMonotoneX,
}

export default Line

// fullstack-d3-advanced-code/14-using-d3-with-angular/src/app/completed/chart/line/line.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core'
import * as d3 from "d3"

@Component({
  selector: '[appLine]',
  template: `
    <svg:path
      [ngClass]="type"
      [attr.d]="lineString"
      [style.fill]="fill">
    </svg:path>
  `,
  styleUrls: ['./line.component.css']
})
export class LineComponent implements OnChanges {
  @Input() type: "area" | "line" = "line"
  @Input() data: Object[]
  @Input() xAccessor: Function
  @Input() yAccessor: Function
  @Input() y0Accessor?: Function
  @Input() interpolation?: Function = d3.curveMonotoneX
  @Input() fill?: string
  private lineString: ""

  updateLineString(): void {
    const lineGenerator = d3[this.type]()
    .x(this.xAccessor)
    .y(this.yAccessor)
    .curve(this.interpolation)

    if (this.type == "area") {
      lineGenerator
        .y0(this.y0Accessor)
        .y1(this.yAccessor)
    }

    this.lineString = lineGenerator(this.data)
  }

  ngOnChanges(changes: SimpleChanges): void {
    this.updateLineString()
  }

}
