// examples/13-using-d3-with-react-js/src/completed/Chart/Bars.jsx
import React from "react"
import PropTypes from "prop-types"
import * as d3 from 'd3'
import { accessorPropsType, useAccessor } from "./utils";

const Bars = ({ data, keyAccessor, xAccessor, yAccessor, widthAccessor, heightAccessor, ...props }) => (
  <React.Fragment>
    {data.map((d, i) => (
      <rect {...props}
        className="Bars__rect"
        key={keyAccessor(d, i)}
        x={useAccessor(xAccessor, d, i)}
        y={useAccessor(yAccessor, d, i)}
        width={d3.max([useAccessor(widthAccessor, d, i), 0])}
        height={d3.max([useAccessor(heightAccessor, d, i), 0])}
      />
    ))}
  </React.Fragment>
)

Bars.propTypes = {
  data: PropTypes.array,
  keyAccessor: accessorPropsType,
  xAccessor: accessorPropsType,
  yAccessor: accessorPropsType,
  widthAccessor: accessorPropsType,
  heightAccessor: accessorPropsType,
}

Bars.defaultProps = {
}

export default Bars

// fullstack-d3-advanced-code/14-using-d3-with-angular/src/app/completed/chart/bars/bars.component.ts
import { Component, Input } from '@angular/core'
import { useAccessor } from '../utils';

@Component({
  selector: '[appBars]',
  template: `
    <svg:rect
      *ngFor="let bar of data; trackBy: keyAccessor"
      [attr.x]="useAccessor(xAccessor, bar, $index)"
      [attr.y]="useAccessor(yAccessor, bar, $index)"
      [attr.width]="max(useAccessor(widthAccessor, bar, $index), 0)"
      [attr.height]="max(useAccessor(heightAccessor, bar, $index), 0)"
      [attr.fill]="fill || '#9980FA'">
    </svg:rect>
  `,
  styleUrls: ['./bars.component.css']
})
export class BarsComponent {
  @Input() data: Object[]
  @Input() keyAccessor: Function
  @Input() xAccessor: Function
  @Input() yAccessor: Function
  @Input() widthAccessor: Function
  @Input() heightAccessor: Function
  @Input() fill?: string
  private useAccessor: Function = useAccessor
  private max = Math.max
}
