// fullstack-d3-advanced-code/14-using-d3-with-angular/src/app/completed/timeline/timeline.component.ts
import { Component, Input, ViewChild, ElementRef, AfterContentInit, OnChanges, SimpleChanges } from '@angular/core'
import * as d3 from "d3"
import { getUniqueId } from '../chart/utils'
import { DimensionsType, ScaleType } from '../../utils/types'

@Component({
  selector: 'app-timeline',
  templateUrl: './timeline.component.html',
  styleUrls: ['./timeline.component.css'],
  host: {
    '(window:resize)': 'onResize($event)'
  }
})
export class TimelineComponent implements AfterContentInit, OnChanges {
  @Input() data: Array<Object>
  @Input() label: string
  @Input() xAccessor: Function
  @Input() yAccessor: Function
  private dimensions: DimensionsType
  private xScale: ScaleType
  private yScale: ScaleType
  private xAccessorScaled: Function
  private yAccessorScaled: Function
  private y0AccessorScaled: Function
  private formatDate: Function = d3.timeFormat("%-b %-d")
  private gradientId: string = getUniqueId("Timeline-gradient")
  private gradientColors: string[] = ["rgb(226, 222, 243)", "#f8f9fa"]
  @ViewChild('container') container: ElementRef

  constructor() {
    this.dimensions = {
      marginTop: 40,
      marginRight: 30,
      marginBottom: 75,
      marginLeft: 75,
      height: 300,
      width: 600,
    }
    this.dimensions = {
      ...this.dimensions,
      boundedHeight: Math.max(this.dimensions.height
        - this.dimensions.marginTop
        - this.dimensions.marginBottom, 0),
      boundedWidth: Math.max(this.dimensions.width
        - this.dimensions.marginLeft
        - this.dimensions.marginRight, 0),
    }
  }

  updateDimensions() {
    const width = this.container.nativeElement.offsetWidth
    this.dimensions.width = this.container.nativeElement.offsetWidth
    this.dimensions.boundedWidth = Math.max(
      this.dimensions.width
        - this.dimensions.marginLeft
        - this.dimensions.marginRight,
      0
    )
    this.updateScales()
  }

  ngAfterContentInit() {
    this.updateDimensions()
  }

  onResize() {
    this.updateDimensions()
  }

  ngOnChanges(changes: SimpleChanges): void {
    this.updateScales()
  }

  updateScales() {
    this.xScale = d3.scaleTime()
      .domain(d3.extent(this.data, this.xAccessor))
      .range([0, this.dimensions.boundedWidth])

    this.yScale = d3.scaleLinear()
      .domain(d3.extent(this.data, this.yAccessor))
      .range([this.dimensions.boundedHeight, 0])
      .nice()

    this.xAccessorScaled = d => this.xScale(this.xAccessor(d))
    this.yAccessorScaled = d => this.yScale(this.yAccessor(d))
    this.y0AccessorScaled = this.yScale(this.yScale.domain()[0])
  }

}

<div #container>
  <app-chart
    [dimensions]="dimensions">
    <svg:defs>
      <svg:g appGradient
        [id]="gradientId"
        [colors]="gradientColors"
        x2="0"
        y2="100%"
      >
      </svg:g>
    </svg:defs>
    <svg:g appAxis
      dimension="x"
      [dimensions]="dimensions"
      [scale]="xScale"
      [formatTick]="formatDate"
      [label]="label">
    </g>
    <svg:g appAxis
      dimension="y"
      [dimensions]="dimensions"
      [scale]="yScale"
      [label]="label">
    </g>
    <svg:g appLine
      type="area"
      [data]="data"
      [xAccessor]="xAccessorScaled"
      [yAccessor]="yAccessorScaled"
      [y0Accessor]="y0AccessorScaled"
      fill="url(#{{ gradientId }})">
    </svg:g>
    <svg:g appLine
      [data]="data"
      [xAccessor]="xAccessorScaled"
      [yAccessor]="yAccessorScaled">
    </svg:g>
  </app-chart>
</div>

// examples/13-using-d3-with-react-js/src/Timeline.jsx
import React from "react"
import PropTypes from "prop-types"
import * as d3 from "d3"

import Chart from "./completed/Chart/Chart"
import Line from "./completed/Chart/Line"
import Axis from "./Chart/Axis-naive"
import Gradient from "./Chart/Gradient";
import { useChartDimensions, accessorPropsType, useUniqueId } from "./Chart/utils";

const formatDate = d3.timeFormat("%-b %-d")
const gradientColors = ["rgb(226, 222, 243)", "#f8f9fa"]

const Timeline = ({ data, xAccessor, yAccessor, label }) => {
  const [ref, dimensions] = useChartDimensions()

  const xScale = d3.scaleTime()
    .domain(d3.extent(data, xAccessor))
    .range([0, dimensions.boundedWidth])
  
  const yScale = d3.scaleLinear()
    .domain(d3.extent(data, yAccessor))
    .range([dimensions.boundedHeight, 0])
    .nice()

  const xAccessorScaled = d => xScale(xAccessor(d))
  const yAccessorScaled = d => yScale(yAccessor(d))
  // const y0AccessorScaled = yScale(yScale.domain()[0])
  
  return (
    <div className="Timeline" ref={ref}>
      <Chart dimensions={dimensions}>
        <Axis
          dimension="x"
          scale={xScale}
          formatTick={formatDate}
        />
        <Axis
          dimension="y"
          scale={yScale}
          label={label}
        />
        <Line
          data={data}
          xAccessor={xAccessorScaled}
          yAccessor={yAccessorScaled}
        />
      </Chart>
    </div>
  )
}

Timeline.propTypes = {
  data: PropTypes.array,
  xAccessor: accessorPropsType,
  yAccessor: accessorPropsType,
  label: PropTypes.string,
}

Timeline.defaultProps = {
  xAccessor: d => d.x,
  yAccessor: d => d.y,
}

export default Timeline
